stages:
  - lint
  - test
  - report

eslint:
  stage: lint
  image: node:20.11.0
  script:
    - npm ci
    - npm run lint

prettier:
  stage: lint
  image: node:20.11.0
  script:
    - npm ci
    - npm run format

test:
  stage: test
  image: node:20.11.0
  script:
    - npm ci
    - cp .env.example .env
    - npm run test:ci

allure:
  stage: report
  image: registry.gitlab.com/freepad/qajs-2023-12/allure:latest
  script:
    - cd /app
    - npx allure generate allure-results --clean
  artifacts:
    paths:
      - allure-report
